### ISSUE TITLE
Zappa install doesn't work with Python 3.7

### ISSUE THREAD

**Issue by iandees** [tilezen/tapalcatl-py#37]
Hi future self and others that might run into this problem.

I was trying to install Zappa after having upgraded to Python 3.7 and not having any luck. When installing Zappa, I ran into errors while compiling the `pyyaml` package that looked like this:

```
    /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    ext/_yaml.c:24212:24: error: no member named 'exc_type' in 'struct _ts'
        tmp_type = tstate->exc_type;
                   ~~~~~~  ^
    ext/_yaml.c:24213:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
        tmp_value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
    /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    ext/_yaml.c:24214:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
        tmp_tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
    /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    ext/_yaml.c:24215:13: error: no member named 'exc_type' in 'struct _ts'
        tstate->exc_type = local_type;
        ~~~~~~  ^
    ext/_yaml.c:24216:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
        tstate->exc_value = local_value;
                ^~~~~~~~~
                curexc_value
    /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    ext/_yaml.c:24217:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
        tstate->exc_traceback = local_tb;
                ^~~~~~~~~~~~~
                curexc_traceback
    /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    51 warnings and 15 errors generated.
    error: command 'clang' failed with exit status 1

    ----------------------------------------

  Failed building wheel for pyyaml
Command "/Users/ian.dees/.local/share/virtualenvs/tapalcatl-py-NSq2EmQ3/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/g1/sdx4zczd78q3x8y9jzqjcdhc0000gp/T/pip-install-7hxh7ba4/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/g1/sdx4zczd78q3x8y9jzqjcdhc0000gp/T/pip-record-yyt616j2/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ian.dees/.local/share/virtualenvs/tapalcatl-py-NSq2EmQ3/bin/../include/site/python3.7/pyyaml" failed with error code 1 in /private/var/folders/g1/sdx4zczd78q3x8y9jzqjcdhc0000gp/T/pip-install-7hxh7ba4/pyyaml/
```

It looks like [Python 3.7 breaks PyYAML's build](https://stackoverflow.com/questions/51165585/pip3-install-pyyaml-failed-python3-7-macos-high-sierra), so I [installed `pyenv`](https://github.com/pyenv/pyenv#homebrew-on-mac-os-x) and used `pyenv` to install Python 3.6.6, switch to that version and re-install dependencies for tapalcatl-py with `pipenv --rm && pipenv install --dev`.

**Comment by ceefour** [comment]
Related to https://github.com/Miserlou/Zappa/issues/1710
